name: shinobi_self
description: "Shinobi Self: Train Like a Ninja, Grow Like a Hero - A Naruto-themed mental wellness app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.3
  
  # UI and Animations
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  google_fonts: ^5.1.0
  
  # Audio
  audioplayers: ^5.2.1
  
  # Firebase
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # firebase_firestore: ^4.13.6
  # firebase_analytics: ^10.7.4
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  
  # Dependencies from HEAD (kept)
  image_picker: ^1.0.5
  http: ^1.1.0

  # Dependencies from origin/neal (kept)
  animations: ^2.0.8
  simple_animations: ^5.0.2
  flutter_animate: ^4.3.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/
    - assets/sounds/
   # - assets/animations/
   # - assets/icons/
  #  - assets/sounds/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
